### ISSUE TITLE
Not being prompted for updates in KSP 1.8.1

### ISSUE THREAD

**Issue by ccaviness** [linuxgurugamer/KSPAddonVersionChecker#27]
I am not being prompted to update to newer versions.

I have installed KSP AVC 1.4.0.3 into a vanilla KSP 1.8.1 install. On startup, I am not prompted to update to the latest AVC release. If I add other out-of-date mods, they don't prompt to get updated either.

Relevant log line in KSP-AVC.log is probably:

> [Exception 20:17:53.1146010]: System.Net.WebException: The request timed out
>   at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00049] in <376e8c39bbab4f1193a569c8dbe4305c>:0 
>   at System.Net.HttpWebRequest.GetResponse () [0x0000e] in <376e8c39bbab4f1193a569c8dbe4305c>:0 
>   at KSP_AVC.Addon.FetchRemoteInfo () [0x0004d] in <2c9f59d130e44c5aa31d526c3ceb0ad0>:0 
>   at KSP_AVC.Addon.ProcessRemoteInfo (System.Object state) [0x00049] in <2c9f59d130e44c5aa31d526c3ceb0ad0>:0 

(Separate from this issue, I believe the AVC is not going to update for anyone as the URL at https://github.com/linuxgurugamer/KSPAddonVersionChecker/blob/79baf87d23e325c8acc43dbe75512e488d32d8ba/KSP-AVC.version#L3 returns version 1.3.1.0)

This seems to be specific to KSP 1.8.1. I had KSP 1.6.1 available, to I put KSP AVC 1.3.0.3 and an older build of Kerbalism there and it prompted for updates for Kerbalism., as expected.

I am running on macOS 10.15.2.

KSP.log and KSP-AVC.log from vanilla 1.8.1 + KSP AVC 1.4.0.3: 
[KSP.log](https://github.com/linuxgurugamer/KSPAddonVersionChecker/files/3970916/KSP.log)
[KSP-AVC.log](https://github.com/linuxgurugamer/KSPAddonVersionChecker/files/3970926/KSP-AVC.log)

KSP.log and KSP-AVC.log from vanilla 1.8.1 + KSP AVC 1.4.1.1 + older Kerbalism:
[KSP.log](https://github.com/linuxgurugamer/KSPAddonVersionChecker/files/3970933/KSP.log)
[KSP-AVC.log](https://github.com/linuxgurugamer/KSPAddonVersionChecker/files/3970934/KSP-AVC.log)

KSP.log from vanilla 1.6.1 + KSP AVC 1.3.0.3 + old Kerbalism:
[KSP.log](https://github.com/linuxgurugamer/KSPAddonVersionChecker/files/3970946/KSP.log)
[KSP-AVC.log](https://github.com/linuxgurugamer/KSPAddonVersionChecker/files/3970948/KSP-AVC.log)

**Comment by ccaviness** [comment]
Just to verify, I also tried KSP 1.8.1 with KSP AVC 1.3.0.3, and it did not prompt to update old mods.

**Comment by linuxgurugamer** [comment]
Fixed in 1.4.1.1
https://github.com/linuxgurugamer/KSPAddonVersionChecker/releases/tag/1.4.1.1

**Comment by ccaviness** [comment]
No, not fixed for me, at least. 

In my initial comment I posted logs with vanilla KSP 1.8.1 + KSP AVC 1.4.1.1 + an old build of Kerbalism and it did **not** prompt for updates.

KSP 1.6.1 with AVC 1.3.0.3 and the same old build of Kerbalism **did** prompt, as expected.

Also, many of your mods have ksp.spacetux.net URLs for version checks, and they are all returning old versions, so _separately_ from the issue I'm reporting, many of your mods won't prompt for an update until these URLs changed (presumably to the current file on github?) or the data on ksp.spacetux.net is updated.

E.g., the `KSP-AVC.version` URL returns 1.3.1 as the current version:

> $ curl http://ksp.spacetux.net/avc/KSP-AVC
> {
>   "NAME": "KSP-AVC Plugin",
>   "URL": "http://ksp.spacetux.net/avc/KSP-AVC",
>   "DOWNLOAD": "https://github.com/linuxgurugamer/KSPAddonVersionChecker/releases",
>   "GITHUB": {
>     "USERNAME": "linuxgurugamer",
>     "REPOSITORY": "KSPAddonVersionChecker"
>   },
>   "VERSION": {
>     "MAJOR": 1,
>     "MINOR": 3,
>     "PATCH": 1,
>     "BUILD": 0
>   },
>   "KSP_VERSION": {
>     "MAJOR": 1,
>     "MINOR": 5,
>     "PATCH": 1
>   },
>   "KSP_VERSION_MIN": {
>     "MAJOR": 1,
>     "MINOR": 5,
>     "PATCH": 1
>   }
> }
>

**Comment by ccaviness** [comment]
I apologize, my initial comment was perhaps misleading. **Any** version of KSP-AVC, including the latest, does not prompt to update **any** out of date mods, when installed in KSP 1.8.1. A compatible version of KSP AVC installed into KSP 1.6.1 does prompt to update the (same) out of date mods.

**Comment by ccaviness** [comment]
I have a theory. You added a `request.Timeout = 10`, thinking it was seconds, but in fact that's milliseconds.
https://docs.microsoft.com/en-us/dotnet/api/system.net.httpwebrequest.timeout?view=netframework-4.8#property-value
> The number of milliseconds to wait before the request times out. The default value is 100,000 milliseconds (100 seconds).

**Comment by ccaviness** [comment]
https://github.com/linuxgurugamer/KSPAddonVersionChecker/pull/28

**Comment by ccaviness** [comment]
Also sent https://github.com/linuxgurugamer/KSPAddonVersionChecker/pull/29 to update the `.version` file. Not sure if that's how you want to do this, or if you want to/have access to update ksp.spacetux.net.

**Comment by ccaviness** [comment]
@linuxgurugamer See previous messages (and pull requests) above in case you don't see updates on closed issues (and I can't re-open).
